### PR TITLE
fix: Transcript Page feedback 

### LINKED ISSUE #71: Transcript Page Feedback Issues
- Paragraphs on transcript page aren’t captured well on desktop. (Mobile has more spacing between each paragraph — screenshot below)
Screenshot 2024-12-17 at 2 41 36 PM 

Screenshot 2024-12-17 at 2 41 23 PM

- the topic pills are shown as their slug and not the actual name (should be capitalised)
- the extra padding at the bottom of transcript for chapter navigation should be removed

### PR DESCRIPTION
**Pull request by 0tuedon**
To Test,
[Link](https://registry-2xxiapct1-btc-knowledge-base.vercel.app/bitcoin-developers-miners-meeting-2016/cali2016#some-topic-ideas-for-day-2)

This PR also closes #71

### CODE REVIEW

**Comment by 0tuedon** [comment]
@Emmanuel-Develops

File: src/components/common/TranscriptMetadataCard.tsx [hunk 1]
```diff
@@ -38,6 +39,11 @@ const TranscriptMetadataComponent = ({
  
   const formattedDate =   isDate(convertedDate) ? format(convertedDate, "d MMMM, yyyy") : "";
 
+  const topicsWithTitles =  topics.map(topic => {
+    const currentTopic =  allTopics.find( topicData => topicData.slug === topic );
+    return currentTopic;
+  } )
+
```
Comment (kouloumos) [inline src/components/common/TranscriptMetadataCard.tsx:46]: Can we handle this at the Contentlayer level? Specifically, replacing topic slugs with their full names during the Contentlayer processing step. This would eliminate the need to perform the replacement every time we display topic tags, such as on the source page, where this replacement is currently not accounted for:
image

Comment (Emmanuel-Develops) [reply src/components/common/TranscriptMetadataCard.tsx:46]: @0tuedon any update on this?
is the suggestion clear?

Comment (0tuedon) [reply src/components/common/TranscriptMetadataCard.tsx:46]: Yh, I am working on putting the logic on contentlayer the file, this will also fix it for our /topics page

Comment (0tuedon) [reply src/components/common/TranscriptMetadataCard.tsx:46]: > Can we handle this at the Contentlayer level? Specifically, replacing topic slugs with their full names during the Contentlayer processing step. This would eliminate the need to perform the replacement every time we display topic tags, such as on the source page, where this replacement is currently not accounted for


But if we replace the topic slugs with their names then we need to to createSlug everytime we want a link?

Comment (Emmanuel-Develops) [reply src/components/common/TranscriptMetadataCard.tsx:46]: mmm, true.

For clarity, to get the topic name do we unsluggify or we have a lookup with the actual name?
cc: @kouloumos @0tuedon

Comment (0tuedon) [reply src/components/common/TranscriptMetadataCard.tsx:46]: Currently what I did, which @kouloumos pointed out is to find the topics by looping through allTopics and get the name for them. This only fixes it one place at a time.

Comment (0tuedon) [reply src/components/common/TranscriptMetadataCard.tsx:46]: We might need to change it in most places where we do `transcript.tags`. if that's fine I can move on with it

**Comment by Emmanuel-Develops** [comment]
Screenshot 2024-12-18 at 3 27 37 PM
we still have the padding at the bottom @0tuedon 
from the conversation with art yesterday, let's remove the extra padding from both transcript page and explore section

**Comment by 0tuedon** [comment]
>  we still have the padding at the bottom @0tuedon from the conversation with art yesterday, let's remove the extra padding from both transcript page and explore section

Yh this changes is currently on local and i had a conversation with @kouloumos  on the implementation details, i can bring you up to speed with this.
Basically it's about changing it from the transcript contentlayer page.

File: src/components/common/TranscriptMetadataCard.tsx (hunk 1 above)
Comment (0tuedon) [reply src/components/common/TranscriptMetadataCard.tsx:46]: > @0tuedon, how was it done for topics page?

``` const topicsWithTitles =  topics.map(topic => {
    const currentTopic =  allTopics.find( topicData => topicData.slug === topic );
    return currentTopic;
  } )
  ```
  
  we are going with a new approach by adding a field to the transcripts called tagsDetailed temporarily.
  
  and I will push this in a few hours then we test to see no link breaks 
  
  and then I will have another commit to directly overwrite the tags.

Comment (Emmanuel-Develops) [reply src/components/common/TranscriptMetadataCard.tsx:46]: having a new computed field is fine  👍

**Comment by Emmanuel-Develops** [comment]
> Yh this changes is currently on local and i had a conversation with @kouloumos on the implementation details, i can bring you up to speed with this. Basically it's about changing it from the transcript contentlayer page.

this is a different issue, I'm referring to the extra space in the red box which is a styling fix
Screenshot 2024-12-17 at 2 44 42 PM

**Comment by 0tuedon** [comment]
@kouloumos @Emmanuel-Develops , you can test if it's broken anywhere else.

File: contentlayer.config.ts [hunk 2]
```diff
@@ -363,6 +378,31 @@ export const Transcript = defineDocumentType(() => ({
     source_file: { type: "string" },
   },
   computedFields: {
+    tagsDetailed: {
+      type: "list",
+      resolve: (doc) => {
+        const topicsMap = doc?.tags as any || [];
```
Comment (Emmanuel-Develops) [inline contentlayer.config.ts:384]: something like the code below is easier to follow.
Are there instances where tags are not arrays?
```suggestion
        const topics: string[] = [];
        if (Array.isArray(doc?.tags?._array) {
          topics.push(doc.tags._array)
        }
```

File: contentlayer.config.ts [hunk 3]
```diff
@@ -363,6 +378,31 @@ export const Transcript = defineDocumentType(() => ({
...
+        const topics = (topicsMap?._array as string[]) ?? [];
+
+        const topicsWithTitles = topics.map((topic) => {
+          const currentTopic = getTopics().find(
+            (topicData: ContentData) => topicData.slug === topic
```
Comment (Emmanuel-Develops) [inline contentlayer.config.ts:389]: we are not accounting for aliases here, as some tags could fall under aliases in the topic index and not the general tags.

There really isn't an easier way to get that data, we can discuss it further in this pr cc: @kouloumos

File: src/components/common/Pill.tsx [hunk 4]
```diff
@@ -5,7 +5,7 @@ const Pill = ({ name, slug }: { name: string; slug: string }) => {
     <Link
       key={name}
       href={slug || ""}
-      className="max-content py-1 px-4 rounded-[5px] bg-gray-custom-700 hover:bg-gray-custom-600 hover:text-gray-custom-100 max-md:px-3 max-md:py-[2px] text-xs md:text-sm 2xl:text-base max-md:border max-md:border-gray-custom-300 max-md:leading-[100%]"
+      className="max-content first-letter:capitalize py-1 px-4 rounded-[5px] bg-gray-custom-700 hover:bg-gray-custom-600 hover:text-gray-custom-100 max-md:px-3 max-md:py-[2px] text-xs md:text-sm 2xl:text-base max-md:border max-md:border-gray-custom-300 max-md:leading-[100%]"
```
Comment (Emmanuel-Develops) [inline src/components/common/Pill.tsx:8]: we can remove the capitalize since we are using the topic name itself and not the slug

File: src/components/common/TranscriptMetadataCard.tsx [hunk 5]
```diff
@@ -2,21 +2,22 @@
 
 import React, { useState } from "react";
 import Image from "next/image";
+import allTopics from "@/public/topics-counts.json"
```
Comment (Emmanuel-Develops) [inline src/components/common/TranscriptMetadataCard.tsx:5]: allTopics is not used

File: src/components/common/TranscriptMetadataCard.tsx [hunk 6]
```diff
@@ -108,7 +110,7 @@ const TranscriptMetadataComponent = ({
               <div className="flex flex-wrap gap-2">
                 {(topics && topics.length > 0) ?
                   topics.map((topic) => (
-                    <Pill key={topic} name={topic} slug={`/tags/${createSlug(topic)}`} />
+                    <Pill key={topic.slug} name={topic.name || ""} slug={`/tags/${topic.slug}`} />
```
Comment (Emmanuel-Develops) [inline src/components/common/TranscriptMetadataCard.tsx:113]: topic.name will always be defined. you are using the slug as the fallback in contentlayer

File: src/components/explore/ContentGrouping.tsx [hunk 7]
```diff
@@ -40,7 +40,7 @@ const ContentGrouping = ({
       {screen === "desktop" && (
         <div
           className={twMerge(
-            " flex-col p-5 hidden lg:flex gap-2.5 border max-h-[calc(95vh-var(--header-height))] overflow-auto scroller border-gray-custom-1200 rounded-md w-full min-w-[260px] 2xl:min-w-[354px] ",
+            " flex-col p-5 hidden lg:flex gap-2.5 border max-h-[calc(90vh-var(--header-height))] overflow-auto scroller border-gray-custom-1200 rounded-md w-full min-w-[260px] 2xl:min-w-[354px] ",
```
Comment (Emmanuel-Develops) [inline src/components/explore/ContentGrouping.tsx:43]: what was this change for?

Comment (0tuedon) [reply src/components/explore/ContentGrouping.tsx:43]: This was in relation to the padding change

File: contentlayer.config.ts (hunk 2 above)
Comment (0tuedon) [reply contentlayer.config.ts:384]: Yh, because of how content layer does the doc, docs.tags isn't actually an array till you do _array, and for typing we typed tags as an array which we do we need. 

Below is what we get with ```doc?.tags```
Screenshot 2024-12-20 at 10 37 42

I think I could name it better and put a comment there
